name: Auto-Link JIRA Issue

on:
  pull_request:
    types: [ opened ]

jobs:
  autolink:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set branch name
        run: |
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Build JIRA URL
        run: |
          echo "JIRA_URL=https://zeroimpact.atlassian.net/browse/${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Update PR body with JIRA link
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const jiraUrl = process.env.JIRA_URL;
            const currentBody = context.payload.pull_request.body || '';
            const linkLine = `\n\n**JIRA:** ${jiraUrl}`;
            const newBody = currentBody.includes(jiraUrl) ? currentBody : currentBody + linkLine;

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              body: newBody
            });
